# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-01 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grades',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelTable(
            name='grades',
            table='grades',
        ),
        migrations.AlterModelTable(
            name='students',
            table='student',
        ),
    ]
