# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-01 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20190301_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='gdate',
            field=models.DateTimeField(),
        ),
    ]
